In [1]:
import pandas as pd
import numpy as np 
import  matplotlib.pyplot as plt

In [36]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [37]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [38]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [39]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [40]:
dataset['Age']

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [41]:
dataset.Age

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [42]:
dataset[['Age','Salary']]

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [43]:
#iloc= soustraction des donneés

In [8]:
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [14]:
x


Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [10]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [46]:
#y=dataset.iloc[:,-1].values
#y est un numpyarray

In [47]:
dataset['Age'].fillna(dataset['Age'].mean)

0                                                 44.0
1                                                 27.0
2                                                 30.0
3                                                 38.0
4                                                 40.0
5                                                 35.0
6    <bound method NDFrame._add_numeric_operations....
7                                                 48.0
8                                                 50.0
9                                                 37.0
Name: Age, dtype: object

In [48]:
x['Age']=x['Age'].fillna(x['Age'].mean())

In [16]:
x

Country        Age   Salary
0   France  44.000000  72000.0
1    Spain  27.000000  48000.0
2  Germany  30.000000  54000.0
3    Spain  38.000000  61000.0
4  Germany  40.000000      NaN
5   France  35.000000  58000.0
6    Spain  38.777778  52000.0
7   France  48.000000  79000.0
8  Germany  50.000000  83000.0
9   France  37.000000  67000.0

In [46]:
x['Age'].mean()

38.77777777777778

In [49]:
x['Salary']=x['Salary'].fillna(x['Salary'].mean())

In [18]:
x

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

supprimer les valeur manquante

In [50]:
x.fillna({'Salary': x['Salary'].mean(),'Age':int(x['Age'].mean())},inplace=True)

In [20]:
x

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

encoding

In [51]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [52]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [53]:
x=np.array(ct.fit_transform(x))
x=x[:,1:]
x

array([[0.00000000e+00, 0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 0.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [54]:
x=pd.DataFrame(x)
x

0    1          2             3
0  0.0  0.0  44.000000  72000.000000
1  0.0  1.0  27.000000  48000.000000
2  1.0  0.0  30.000000  54000.000000
3  0.0  1.0  38.000000  61000.000000
4  1.0  0.0  40.000000  63777.777778
5  0.0  0.0  35.000000  58000.000000
6  0.0  1.0  38.777778  52000.000000
7  0.0  0.0  48.000000  79000.000000
8  1.0  0.0  50.000000  83000.000000
9  0.0  0.0  37.000000  67000.000000

getdummies

In [55]:
x_df=pd.get_dummies(x,drop_first=True)

In [26]:
x

0    1          2             3
0  0.0  0.0  44.000000  72000.000000
1  0.0  1.0  27.000000  48000.000000
2  1.0  0.0  30.000000  54000.000000
3  0.0  1.0  38.000000  61000.000000
4  1.0  0.0  40.000000  63777.777778
5  0.0  0.0  35.000000  58000.000000
6  0.0  1.0  38.777778  52000.000000
7  0.0  0.0  48.000000  79000.000000
8  1.0  0.0  50.000000  83000.000000
9  0.0  0.0  37.000000  67000.000000

labelEncoder

In [56]:
ct1=ColumnTransformer(transformers=[('encoder',LabelEncoder,[0])],remainder='passthrough')

In [28]:
le=LabelEncoder()

In [29]:
y=le.fit_transform

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [59]:
X_train

0    1          2             3
4  1.0  0.0  40.000000  63777.777778
9  0.0  0.0  37.000000  67000.000000
1  0.0  1.0  27.000000  48000.000000
6  0.0  1.0  38.777778  52000.000000
7  0.0  0.0  48.000000  79000.000000
3  0.0  1.0  38.000000  61000.000000
0  0.0  0.0  44.000000  72000.000000
5  0.0  0.0  35.000000  58000.000000

In [60]:
x

0    1          2             3
0  0.0  0.0  44.000000  72000.000000
1  0.0  1.0  27.000000  48000.000000
2  1.0  0.0  30.000000  54000.000000
3  0.0  1.0  38.000000  61000.000000
4  1.0  0.0  40.000000  63777.777778
5  0.0  0.0  35.000000  58000.000000
6  0.0  1.0  38.777778  52000.000000
7  0.0  0.0  48.000000  79000.000000
8  1.0  0.0  50.000000  83000.000000
9  0.0  0.0  37.000000  67000.000000

normalisation

In [139]:
#normalisation:x-min(x)/max(x)-min(x) MinMax:normalisation entre [0.1]

In [140]:
#standarisation : x=x-mean(x)/ecartype(x)

In [ ]:
#pas de scaling sur les variables encoder

In [63]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [64]:
scaler =StandardScaler()


In [65]:
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [66]:
X_train

array([[ 2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [-0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [-0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [-0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [-0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [67]:
X_test

array([[ 2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [ 2.64575131, -0.77459667,  1.98496442,  2.13981082]])